force-app/main/default/objects/Batch_Job_Setting__mdt/Batch_Job_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Sets up settings for batch jobs</description>
    <label>Batch Job Setting</label>
    <pluralLabel>Batch Job Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Setting__mdt/fields/Number_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Number_To_Delete__c</fullName>
    <description>Value is the number of records to be deleted as part of a scheduled batch job</description>
    <label>Number To Delete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>According to the data model, the Interactions model is created when a web-form is submitted (or some other client action is taken) and tracks each interaction made by an individual over time.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteOldInteractions.cls
public class DeleteOldInteractions implements Database.Batchable<sObject> {
    
       
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return  Database.getQueryLocator(
        	[Select Id From Interaction__c Where createdDate < :Date.today().addDays(-3)]
        );
        
    }
    
    public void execute(Database.BatchableContext bc, List<Interaction__c> scope){
        
        Batch_Job_Setting__mdt batchJobSetting = [Select Number_To_Delete__c From Batch_Job_Setting__mdt Limit 1];
                
        Integer num = Integer.valueOf(batchJobSetting.Number_To_Delete__c);
                
        List<Interaction__c> intns = new List<Interaction__c>();
        for(Integer i = 0; i < num; i++){
            intns.add(scope[i]);
        }
              
        delete intns;
        
    }
    public void finish(Database.BatchableContext bc){
        
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
    }
}