force-app/main/default/objects/Interaction__c/Interaction__c.object-meta.xml
<CustomObject>
    <description>According to the data model, the Interactions model is created when a web-form is submitted (or some other client action is taken) and tracks each interaction made by an individual over time.</description>
    <label>Interaction</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Placeholder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestInteractionToolsRest.cls
@isTest
public class TestInteractionToolsRest {
    @isTest static void testCreateInteraction(){
       // Call the method to test
       ID thisIntnId = InteractionToolsRest.createInteraction('myName','myLastName','myname.mylastname@email.com',
                                                              '337-373-7733', '373 thisStreet', 'thisCity', 'ST', '37373','Placeholder','Web','thisCmpy');
       // Verify results
       System.assert(thisIntnId != null);
        
       Interaction__c thisIntn = [SELECT Id, Email__c, Source__c FROM Interaction__c WHERE Id=:thisIntnId];
       System.assert(thisIntn != null);
       System.assertEquals(thisIntn.Email__c, 'myname.mylastname@email.com');
       System.assertNotEquals(thisIntn.Source__c, 'Phone');
    }
    
}